solicitud_ritt_index:
    path:     /
    defaults: { _controller: SieRieBundle:SolicitudRITT:index }

solicitud_ritt_guarda_tramite:
    path:     /rittGuardaTramite
    defaults: { _controller: SieRieBundle:SolicitudRITT:guardaTramite }

solicitud_ritt_lista_Nac:
    path:     /rittListatramites
    defaults: { _controller: SieRieBundle:SolicitudRITT:ListaTramitesNac }

solicitud_ritt_guarda_tramite_nac:
    path:     /rittGuardaTramiteNac
    defaults: { _controller: SieRieBundle:SolicitudRITT:guardaTramiteNac }

solicitud_ritt_certificados_Nac:
    path:     /rittListatramitesCertificados
    defaults: { _controller: SieRieBundle:SolicitudRITT:ListaTramitesCertificadoNac }

solicitud_ritt_guarda_tramite_imprime:
    path:     /rittGuardaTramiteNacImprime
    defaults: { _controller: SieRieBundle:SolicitudRITT:guardaTramiteNacImprime }

solicitud_ritt_vista_previa_certificado:
    path:     /rittVistaPreviaCertificado
    defaults: { _controller: SieRieBundle:SolicitudRITT:vistaPreviaCertificado }

solicitud_ritt_tramite_obs:
    path:     /rittGuardaTramiteNacObs
    defaults: { _controller: SieRieBundle:SolicitudRITT:TramiteObs }

solicitud_ritt_lista_concluidos:
    path:     /rittListaTramitesConcluidos
    defaults: { _controller: SieRieBundle:SolicitudRITT:listaTramitesConcluidos }