herramienta_ceducativa_index:
    path:     /
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:index}
         
sie_alt_ges_sub_sem_open:
    path:     /{teid}/{gestion}/{subcea}/{semestre}/{idiesuc}/gessubsemopen/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:gessubsemopen}  
    options:
         expose: true
         
sie_alt_ges_sub_sem_tramite_solicitud:
    path:     /{idiesuc}/gessubsemtramitesolicitud/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:gessubsemtramitesolicitud}  
    options:
         expose: true  
         
sie_alt_ges_sub_sem_panel_operativos:
    path:     /gessubsempaneloperativos/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:paneloperativos}  
    options:
         expose: true 
         
sie_alt_ges_sub_sem_tramite_solicitud_cambiar_estado_a_regularizado:
    path:     /{iestid}/gessubsemtramitesolicitudcambiarestado/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:gessubsemtramitesolicitudcambiarestado}  
    options:
         expose: true          

herramienta_ceducativa_menu_principal:
    path:     /menuprincipalopen/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:menuprincipalopen}
    
#herramienta_ceducativa_generar_inicio:
#    path:     /{gestion}/{subcea}/{semestre}/generarinicio/
#    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:generarinicio}   
    
herramienta_ceducativa_update:
    path:     /update/
    defaults: { _controller: "SieHerramientaAlternativaBundle:Institucioneducativa:update" }
    methods:  [POST, PUT]  
    
herramienta_ceducativa_cerrar_operativo:
    path:     /cerraroperativo/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:cerraroperativo}
    options:
        expose: true

herramienta_ceducativa_cerrar_operativo_especializados:
    path:     /cerraroperativoesp/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:cerraroperativoespecializados}
    options:
        expose: true
                
herramienta_ceducativa_distrito_listaceas:
    path:     /listaceas/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:listadisceas}         
    options:
         expose: true

herramienta_ceducativa_seleccionar_cea:
    path:     /seleccionarcea/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:seleccionarcea}

herramienta_ceducativa_registro_jurisdiccion_subcea:
    path:     /registro/jurisdiccion/subcea
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:registraJurisdiccionSubCea}    

herramienta_ceducativa_registro_jurisdiccion_subcea_save:
    path:     /save/jurisdiccion/subcea
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:saveJurisdiccionSubCea} 
    
herramienta_ceducativa_buscar_cea:
    path:     /buscarcea/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:buscarcea}    
    methods:  [GET]
    
herramienta_ceducativa_abrir_cea:
    path:     /{ie_id}/{ie_nombre}/abrircea/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:abrircea} 
    options:
         expose: true

herramientalt_ceducativa_crear_periodo:
    path:     /crearPeriodo/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:crearPeriodo}

herramientalt_ceducativa_crear_periodo_cea:
    path:     /crearPeriodoCea/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:crearPeriodoCea}

herramientalt_ceducativa_crear_sucursal:
    path:     /crearSucursal/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:crearSucursal}

herramientalt_ceducativa_crear_sucursal_cea:
    path:     /crearSucursalCea/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:crearSucursalCea}

sie_alt_ges_sub_sem_ceas_pendinte:
    path:     /ceaspendientes/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:ceaspendientes}
    options:
         expose: true

sie_alt_ges_sub_sem_ceas_pendinte_lista:
    path:     /ceaspendientes/lista
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:listaceaspendientes}
         

herramientalt_ceducativa_estadistiscas_cierre:
    path:     /ceasstdcierre/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:ceasstdcierre}
    options:
         expose: true         
         
sie_alt_ges_rudes_user:
    path:     /ceasrudeuser/
    defaults: { _controller: SieHerramientaAlternativaBundle:Default:ceasrudeuser}
    options:
         expose: true 
         
sie_alt_ges_sub_sem_tramite_continuar_sig_operativo:
    path:     /{iestid}/tramitecontinuaroperativo/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:tramitecontinuaroperativo}  
    options:
         expose: true    
         
herramientalt_ceducativa_estadistiscas_departamento:
    path:     /deptoestadsiticas/
    defaults: { _controller: SieHerramientaAlternativaBundle:Estadisticas:ceasstdcierre}
    options:
         expose: true

sie_alt_submenu_diversa:
    path:     /sie/submenuDiversa
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:submenuDiversa}
    options:
         expose: true

sie_alt_reportes_diversa:
    path:     /sie/reportesDiversa
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:reporteDiversa}
    options:
         expose: true

sie_alt_submenu_alterprimaria:
    path:     /submenuAlterPrimaria
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:submenuAlterPrimaria}
    options:
        expose: true

sie_alt_reportes_alterprimaria:
    path:     /reportesAlterPrimaria
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:reporteAlterPrimaria}
    options:
        expose: true

sie_alt_manuales:
    path:     /sie/manuales
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:manuales}

sie_alt_bjp_rue_clistarmenu:
    path:     /bjplistarmenu/{idM}/{pertUM}/{pertP}/{cea}/{umt}/{pt}
    defaults: { _controller: "SieHerramientaAlternativaBundle:EstudianteInscripcionSocioeconomicoAlternativa:listarmenu" }
    options:
         expose: true

sie_alt_bjp_rue_tipomili:
    path:     /bjptipomili/{idUM}/{pertUM}
    defaults: { _controller: "SieHerramientaAlternativaBundle:EstudianteInscripcionSocioeconomicoAlternativa:tipomili" }
    options:
         expose: true

sie_alt_bjp_rue_tipopenal:
    path:     /bjptipopenal/{idP}/{pertP}
    defaults: { _controller: "SieHerramientaAlternativaBundle:EstudianteInscripcionSocioeconomicoAlternativa:tipopenal" }
    options:
         expose: true

sie_alt_clistarprovincias:
    path:     /bjplistarprovincias/{dpto}
    defaults: { _controller: "SieHerramientaAlternativaBundle:Institucioneducativa:listarprovincias" }
    options:
         expose: true
         
sie_alt_clistarmunicipios:
    path:     /bjplistarmunicipios/{prov}
    defaults: { _controller: "SieHerramientaAlternativaBundle:Institucioneducativa:listarmunicipios" }
    options:
         expose: true         

sie_alt_clistarcantones:
    path:     /bjplistarcantones/{muni}
    defaults: { _controller: "SieHerramientaAlternativaBundle:Institucioneducativa:listarcantones" }
    options:
         expose: true               

sie_alt_clistarlocalidades:
    path:     /bjplistarlocalidades/{cantn}
    defaults: { _controller: "SieHerramientaAlternativaBundle:Institucioneducativa:listarlocalidades" }
    options:
         expose: true            

sie_alt_clistardistritos:
    path:     /bjplistardistritos/{dpto}
    defaults: { _controller: "SieHerramientaAlternativaBundle:Institucioneducativa:listardistritos" }
    options:
         expose: true

sie_alt_ges_sub_sem_panel_operativos_lista:
    path:     /gessubsempaneloperativoslista/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:paneloperativoslista}  

sie_alt_ges_sub_sem:
    path:     /gessubsem/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:gessubsem}  
    options:
         expose: true

herramientalt_ceducativa_lista_gestion:
    path:     /ceducativaListaGestion/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:ceducativaListaGestion}

herramientalt_ceducativa_lista_subcea:
    path:     /ceducativaListaSubcea/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:ceducativaListaSubcea}

sie_alt_ges_sub_sem_panel_operativos_observaciones:
    path:     /gessubsempaneloperativosobservaciones/
    defaults: { _controller: SieHerramientaAlternativaBundle:Institucioneducativa:paneloperativosobservaciones}  




