bach_exc:
    path:     /
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:index" }

bach_exc_dir:
    path:     /index-dir
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:indexDir" }
    
bach_exc_rst:
    path:     /index-rst
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:indexRst" }    

bach_exc_ddjj:
    path:     /index-ddjj
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:declaracionJurada" }

bach_exc_ddjj_dir:
    path:     /index-ddjj-dir
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:declaracionJuradaDir" }
    
bach_exc_ie_search:
    path:     /ie-search
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:resultSearchIe" }
    methods:  POST

bach_exc_ie_dir_search:
    path:     /ie-dir-search
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:resultSearchIeDir" }
    methods:  POST  
    
bach_exc_ie_rst_search:
    path:     /ie-rst-search
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:resultSearchIeRst" }
    methods:  POST      

test_bachiller:
    path:     /be-create2023
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:createEstudianteDestacado2023" }    
    options:
         expose: true

bach_exc_create:
    path:     /be-create
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:beCreate" }
    options:
         expose: true


bach_exc_student_info:
    path:     /be-student/{estId}/{estinsId}/{instId}/{genId}
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:infoStudent" }    
    options:
        expose: true
        
ie_autocomplete:
    path: /ie-autocomplete
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:getIes" }

cta_banc_dir_create:
    path:     /cta-create
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:dirCtaCreate" }
    options:
         expose: true        

bach_exc_imprime:
    path:     /imprime-ddj
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:impresionDDJJ" }
    
bach_exc_imprime_dir:
    path:     /imprime-ddj-dir
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:impresionDDJJDir" }    

bach_exc_imprime_consulta2023:
    path:     /imprime-consulta2023
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:impresionConsulta2023" }

bach_exc_imprime_consulta2023_fem:
    path:     /imprime-consulta2023-fem
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:impresionConsulta2023Fem" }

cta_banc_dir_rst2023:
    path:     /estado-dir2023
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:dirCtaRst2023" }  
    options:
        expose: true        

cta_banc_dir_rst:
    path:     /{ie}/estado-dir
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:dirCtaRst" }    

bach_exc_pf_rst:    
    path:     /{ie}/{ed}/{g}/estado-be
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:beRst" }    

bach_exc_rep_dis:
    path:     /index-repdis
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:indexReporteDistrito" }

bach_exc_rep_dist_search:
    path:     /repdis-search
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:resultSearchDistRep" }
    methods:  POST    

bach_exc_completar_informacion_lista:
    path:     /completar-expedido-lista
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:completarInformacionLista" }
    methods:  GET    

bach_exc_completar_informacion_update:
    path:     /updateMaestroCuentabancaria
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:updateMaestroCuentabancaria" }
    options:
        expose: true

bach_exc_completar_informacion_reset_expedido:
    path:     /resetExpedidoMaestroCuentabancaria
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:resetExpedidoMaestroCuentabancaria" }
    options:
        expose: true

bach_exc_imprime_reporte_general:
    path:     /imprime-reporte-general-ibd
    defaults: { _controller: "SieAppWebBundle:BachillerExcelencia:impresionReporteGeneral" }