download_estudiantes_nivelacion:
    path: /listEstudiantesNivelacion/{sie}/{gestion}
    defaults: { _controller: SieAppWebBundle:Download:listadoEstudiantesNivelacion }

download_estudiantes_nivelacionttg:
    path: /listEstudiantesNivelacionttg/{sie}/{gestion}
    defaults: { _controller: SieAppWebBundle:Download:listadoEstudiantesNivelacionttg }

download_tramite_modificacion_calificaciones:
    path: /tramiteModificacionCalificaciones/{idTramite}
    defaults: { _controller: SieAppWebBundle:Download:tramiteModificacionCalificaciones }

donwload_nnats:
    path: /nnats/{gestion}/{sie}
    defaults: { _controller: SieAppWebBundle:Download:nnats }
    options:
        expose: true

download_ddjjone_web:
    path:    /ddjjone/{rude}/{gestion}/{sie}
    defaults: { _controller: SieAppWebBundle:Download:ddjjone }

download_ddjjgroup_web:
    path:   /ddjjgroup/{gestion}/{sie}
    defaults: { _controller: SieAppWebBundle:Download:ddjjgroup}

donwload_listStudentPerCourse:
    path: /listStudentPerCourse/{ue}/{gestion}/{nivel}/{grado}/{paralelo}/{turno}
    defaults: { _controller: SieAppWebBundle:Download:listStudentPerCourse }

donwload_listStudentPerCourseSeg:
    path: /listStudentPerCourseSeg/{ue}/{gestion}/{nivel}/{grado}/{paralelo}/{turno}
    defaults: { _controller: SieAppWebBundle:Download:listStudentPerCourseSeg }

donwload_listStudentPerUe:
    path: /listStudentPerUe/{ue}/{gestion}
    defaults: { _controller: SieAppWebBundle:Download:listStudentPerUe }

donwload_listStudentPerUeSeg:
    path: /listStudentPerUeSeg/{ue}/{gestion}
    defaults: { _controller: SieAppWebBundle:Download:listStudentPerUeSeg }

donwload_listStudentPerUeUnAcredited:
    path: /listStudentPerUe/{sie}
    defaults: { _controller: SieAppWebBundle:Download:listStudentPerUeUnAcredited }

donwload_listStudentPerUeTecnicoHumanistico:
    path: /listStudentPerUeTecnicoHumanistico/{uetu}/{gestion}
    defaults: { _controller: SieAppWebBundle:Download:listStudentPerUeTecnicoHumanistico }

download_distrito_sie_download:
    path:     /download/{file}
    defaults: { _controller: SieAppWebBundle:Download:downloaddistrito }

download_distrito_sie_downloadxls:
    path:     /downloadxls/{file}
    defaults: { _controller: SieAppWebBundle:Download:downloaddistritoxls }

download_distrito_sie_downloadinfoInscritos:
    path:     /downloadinfoInscritos
    defaults: { _controller: SieAppWebBundle:Download:downloadinfoInscritos }

download_ue_solicitudModificacionCalificaciones:
    path:     /djSolicitudModificacionCalificaciones/{idSolicitud}
    defaults: { _controller: SieAppWebBundle:Download:solicitudModificacionCalificaciones }

download_ue_solicitudAdicionCalificaciones:
    path:     /djSolicitudAdicionCalificaciones/{idSolicitud}
    defaults: { _controller: SieAppWebBundle:Download:solicitudAdicionCalificaciones }

download_ue_list_gral_tec_hum:
    path:     /listgraltechum
    defaults: { _controller: SieAppWebBundle:Download:listgraltechum }

download_ue_list_gral_tec_hum_xls:
    path:     /listgraltechumxls
    defaults: { _controller: SieAppWebBundle:Download:listgraltechumxls }

download_ue_list_resumen_tec_hum:
    path:     /listresumentechum
    defaults: { _controller: SieAppWebBundle:Download:resumentechum }

download_ue_reportes_departamento:
    path:    /reportedepartamento/
    defaults: { _controller: SieAppWebBundle:Download:departamentoreporte }

download_ue_reportes_distrito:
    path:    /reportedistrito/
    defaults: { _controller: SieAppWebBundle:Download:distritoreporte }

donwload_boletinPromoPerUe:
    path: /boletinPromoPerUe/{ue}/{nivel}/{ciclo}/{grado}/{paralelo}/{turno}/{gestion}/{itemsUe}
    defaults: { _controller: SieAppWebBundle:Download:boletinPromoPerUe }

donwload_boletinPromoPerUeNewVersion:
    path: /boletinPromoPerUe/{version}/{ue}/{nivel}/{ciclo}/{grado}/{paralelo}/{turno}/{gestion}/{itemsUe}
    defaults: { _controller: SieAppWebBundle:Download:boletinPromoPerUeNewVersion }    

donwload_listMaestrosPerUe:
    path: /listMaestrosPerUe/{ue}/{nivel}/{ciclo}/{grado}/{paralelo}/{turno}/{gestion}/{itemsUe}
    defaults: { _controller: SieAppWebBundle:Download:listMaestrosPerUe }

download_ddjjStudent_web:
    path:    /ddjjStudentWeb/{rude}/{gestion}/{sie}
    defaults: { _controller: SieAppWebBundle:Download:ddjjStudentWeb }

download_libreta:
    path:    /downloadLibreta/{idInscripcion}/{rude}/{sie}/{gestion}/{nivel}/{grado}/{paralelo}/{turno}/{ciclo}
    defaults: { _controller: SieAppWebBundle:Download:downloadLibreta }

download_cut:
    path:    /downloadcut/{idInscripcion}/{rude}/{sie}/{gestion}/{nivel}/{grado}/{paralelo}/{turno}/{ciclo}
    defaults: { _controller: SieAppWebBundle:Download:downloadCut }

download_ddjj_speciality:
    path:    /ddjjSpecialityStudent/{idInscripcion}/{rude}/{sie}/{gestion}/{nivel}/{grado}/{paralelo}/{turno}/{ciclo}
    defaults: { _controller: SieAppWebBundle:Download:ddjjSpecialityStudent }

gestionUesprocesoApertura_listStudentsNoAcreditados:
    path:    /listStudentsNoAcreditados/
    defaults: { _controller: SieAppWebBundle:Download:listStudentsNoAcreditados }

download_rude:
    path:    /downloadrude/{codue}/{rude}/{gestion}/{eins}
    defaults: { _controller: SieAppWebBundle:Download:downloadRude }

donwload_report_rude_operativo:
    path: /reportRudeOperatvio/{codDistrito}
    defaults: { _controller: SieAppWebBundle:Download:reportRudeOperatvio }

download_reporte_gis:
    path:    /downloadReporteGis/{codEdificio}
    defaults: { _controller: SieAppWebBundle:Download:downloadReporteGis }
    options:
        expose: true

donwload_especial_libreta:
    path: /especialLibreta/{infoUe}/{gestion}/{estInsEspId}/{estInsId}/{codigoRude}
    defaults: { _controller: SieAppWebBundle:Download:especialLibreta }

build_archs_olimpiadas_txt:
    path: /buildArchsOlimpiadas/{gestion}
    defaults: { _controller: SieAppWebBundle:Download:buildArchsOlimpiadasTxt }
    options:
        expose: true

download_archs_olimpiadas_txt:
    path: /downloadArchsOlimpiadas
    defaults: { _controller: SieAppWebBundle:Download:downloadArchsOlimpiadasTxt }
    options:
        expose: true

build_archs_olimpiadas_robotica_txt:
    path: /buildArchsOlimpiadasRobotica/{gestion}
    defaults: { _controller: SieAppWebBundle:Download:buildArchsOlimpiadasRoboticaTxt }
    options:
        expose: true

download_archs_olimpiadas_robotica_txt:
    path: /downloadArchsOlimpiadasRobotica
    defaults: { _controller: SieAppWebBundle:Download:downloadArchsOlimpiadasRoboticaTxt }
    options:
        expose: true

donwload_listainscritosestudiantesolim:
    path: /listainscritosestudiantesolim/{codges}/{coddis}
    defaults: { _controller: SieAppWebBundle:Download:listainscritosestudiantesolim }

donwload_studentHistModification:
    path:     /downstudentHistModification/{id}/{studentId}
    defaults: { _controller: SieAppWebBundle:Download:downstudentHistModification }

donwload_studentBthEspecialidades:
    path:     /downstudentEspecialidades/{ue}/{gestion}/{gradoId}
    defaults: { _controller: SieAppWebBundle:Download:bthEspecialidades }

donwload_studentBthEspecialidadesEliminadas:
    path:     /downstudentEspecialidadesEliminadas/{ue}/{gestion}/{gradoId}
    defaults: { _controller: SieAppWebBundle:Download:bthEspecialidadesEliminadas }

donwload_boletinNivelacionTTGBth:
    path:     /boletinNivelacionTTGBth/{iecId}/{codue}
    defaults: { _controller: SieAppWebBundle:Download:boletinNivelacionTTGBth }

donwload_boletinNivelacionTTEBth:
    path:     /boletinNivelacionTTEBth/{iecId}/{codue}
    defaults: { _controller: SieAppWebBundle:Download:boletinNivelacionTTEBth }    