reporte_regular_index:
    path:     /
    defaults: { _controller: SieAppWebBundle:Reporte:index }

reporte_regular_informacion_general:
    path:     /informacion/general/regular
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralRegular }

reporte_regular_informacion_general_unidad_educativa:
    path:     /informacion/general/regular/unidad/educativa
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralRegularInstitucionEducativa }

reporte_informacion_general_institutos_tecnicos:
    path:     /informacion/general/institutos/tecnicos
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralInstitutosTecnicos }

reporte_regular_informacion_general_unidad_educativa_lista_print_xls:
    path:     /informacion/general/regular/unidad/educativa/lista/print/xls
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralRegularInstitucionEducativaListaPrintXls }

reporte_informacion_general_ritt_lista_print_xls:
    path:     /informacion/general/institutos/tecnicos/tecnologicos/lista/print/xls
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralInstitutosTecnicosListaPrintXls }

reporte_informacion_general_ritt_lista_print_pdf:
    path:     /informacion/general/institutos/tecnicos/tecnologicos/lista/print/pdf
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralInstitutosTecnicosListaPrintPdf }

reporte_regular_informacion_general_chart:
    path:     /informacion/general/regular/chart
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralRegularChart }
    options:
         expose: true 

reporte_regular_informacion_general_print_pdf:
    path:     /informacion/general/regular/print/pdf
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralRegularPrintPdf }

reporte_regular_informacion_general_print_pdf_temp:
    path:     /informacion/general/regular/print/pdf/temp
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralRegularPrintPdfTemp }


reporte_regular_informacion_general_print_xls:
    path:     /informacion/general/regular/print/xls
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralRegularPrintXls }


reporte_regular_informacion_general_valoracion_cuantitativa_endesarrollo_print_pdf:
    path:     /informacion/general/regular/valoracion/cuantitativa/endesarrollo/print/pdf
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralRegularValoracionCuantitativaEnDesarrolloPrintPdf }

reporte_regular_informacion_general_valoracion_cuantitativa_endesarrollo_print_xls:
    path:     /informacion/general/regular/valoracion/cuantitativa/endesarrollo/print/xls
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralRegularValoracionCuantitativaEnDesarrolloPrintXls }

reporte_regular_subida_archivos:
    path:     /archivos/regular
    defaults: { _controller: SieAppWebBundle:Reporte:subidaArchivosRegular }

reporte_regular_directorio_institucioneducativa:
    path:     /directorio/institucioneducativa/regular
    defaults: { _controller: SieAppWebBundle:Reporte:directorioInstitucionEducativaRegular }

reporte_regular_directorio_institucioneducativa_busqueda:
    path:     /directorio/institucioneducativa/busqueda/regular
    defaults: { _controller: SieAppWebBundle:Reporte:directorioInstitucionEducativaBusquedaRegular }

reporte_regular_directorio_institucioneducativa_detalle:
    path:     /directorio/institucioneducativa/detalle/regular
    defaults: { _controller: SieAppWebBundle:Reporte:directorioInstitucionEducativaDetalleRegular }

reporte_regular_juegos_plurinacionales_nacional_pdf:
    path:    /informacion/general/regular/juegos/nacional/fase/{fase}
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralJuegosNacionalFasePdf } 

reporte_olimpiada_reporteOlimUE_pdf:
    path:    /reporteOlimUE
    defaults: { _controller: SieAppWebBundle:Reporte:reporteOlimUE } 

reporte_especial_index:
    path:     /especial
    defaults: { _controller: SieAppWebBundle:Reporte:especialIndex }

reporte_especial_informacion_general_print_pdf:
    path:     /informacion/general/especial/print/pdf
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralEspecialPrintPdf }

reporte_especial_informacion_general_print_xls:
    path:     /informacion/general/especial/print/xls
    defaults: { _controller: SieAppWebBundle:Reporte:informacionGeneralEspecialPrintXls }

reporte_especial_centro_educativo_index:
    path:     /especial/centro/educativo
    defaults: { _controller: SieAppWebBundle:Reporte:especialInstitucionEducativaIndex }

reporte_especial_centro_educativo_pdf:
    path:     /especial/centro/educativo/pdf
    defaults: { _controller: SieAppWebBundle:Reporte:especialInstitucionEducativaPdf }

reporte_especial_centro_educativo_xls:
    path:     /especial/centro/educativo/xls
    defaults: { _controller: SieAppWebBundle:Reporte:especialInstitucionEducativaXls }

reporte_adultos_index:
    path:     /adultos
    defaults: { _controller: SieHerramientaAlternativaBundle:Estadisticas:alternativaIndex }

reporte_superior_directorio_itts:
    path:     /directorio/itts/superior
    defaults: { _controller: SieAppWebBundle:Reporte:directorioItts }

reporte_superior_directorio_itts_busqueda:
    path:     /directorio/itts/busqueda/superior
    defaults: { _controller: SieAppWebBundle:Reporte:directorioIttsBusquedaSuperior }

reporte_superior_directorio_itts_detalle:
    path:     /directorio/itts/detalle/superior
    defaults: { _controller: SieAppWebBundle:Reporte:directorioIttsDetalleSuperior }

reporte_diversa_index:
    path:     /diversa
    defaults: { _controller: SieHerramientaAlternativaBundle:EstadisticasDiversa:diversaIndex }

reporte_permanente_index:
    path:     /permanente
    defaults: { _controller: SiePermanenteBundle:EstadisticasPermanente:permanenteIndex }

reporte_infraestructura_index:
    path:     /infraestructura
    defaults: { _controller: SieAppWebBundle:EstadisticasInfraestructura:infraestructuraIndex }

estadistica_gerenciales_pdf:
    path:     /informacion/infraestructura/gerencial/print/pdf
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesGerencialesPdf }  

estadistica_infra_ambientes_pdf:
    path:     /informacion/infraestructura/ambientes/print/pdf
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesAmbientesPdf }

estadistica_infra_ambientes_xls:
    path:     /informacion/infraestructura/ambientes/print/xls
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesAmbientesXls }

estadistica_infra_ambientes_pedagogicos_pdf:
    path:     /informacion/infraestructura/ambientes/pedagogico/print/pdf
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesAmbientesPedagogicosPdf }

estadistica_infra_ambientes_pedagogicos_xls:
    path:     /informacion/infraestructura/mbientes/pedagogico/print/xls
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesAmbientesPedagogicosXls }

estadistica_infra_ambientes_no_pedagogicos_pdf:
    path:     /informacion/infraestructura/mbientes/nopedagogico/print/pdf
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesAmbientesNoPedagogicosPdf }

estadistica_infra_ambientes_no_pedagogicos_xls:
    path:     /informacion/infraestructura/mbientes/nopedagogico/print/xls
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesAmbientesNoPedagogicosXls }

estadistica_infra_ambientes_otros_pdf:
    path:     /informacion/infraestructura/mbientes/otros/print/pdf
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesAmbientesOtrosPdf }

estadistica_infra_ambientes_otros_xls:
    path:     /informacion/infraestructura/mbientes/otros/print/xls
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesAmbientesOtrosXls }

estadistica_infra_ambientes_pedagogicos_recreativo_pdf:
    path:     /informacion/infraestructura/ambientes/pedagogico/recreativo/print/pdf
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesAmbientesPedagogicosRecreativosPdf }

estadistica_infra_ambientes_pedagogicos_recreativo_xls:
    path:     /informacion/infraestructura/ambientes/pedagogico/recreativo/print/xls
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesAmbientesPedagogicosRecreativosXls }

estadistica_infra_servicios_pdf:
    path:     /informacion/infraestructura/servicios/print/pdf
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesServiciosPdf }

estadistica_infra_servicios_xls:
    path:     /informacion/infraestructura/servicios/print/xls
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesServiciosXls }

estadistica_infra_eventos_pdf:
    path:     /informacion/infraestructura/eventos/print/pdf
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesEventosPdf }

estadistica_infra_eventos_xls:
    path:     /informacion/infraestructura/eventos/print/xls
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesEventosXls }

estadistica_infra_riesgos_pdf:
    path:     /informacion/infraestructura/riesgos/print/pdf
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesRiesgosPdf }

estadistica_infra_riesgos_xls:
    path:     /informacion/infraestructura/riesgos/print/xls
    defaults: { _controller: SieInfraestructuraBundle:Estadisticas:reportesRiesgosXls }