olimrobotica_index:
    path:     /
    defaults: { _controller: "SieOlimpiadasBundle:OlimRobotica:index" }

olimrobotica_findGrupo:
    path:     /findGrupo
    defaults: { _controller: "SieOlimpiadasBundle:OlimRobotica:findEstudiante" }
    options:
        expose: true

olimrobotica_actualizarCategoria:
    path:     /actualizarCategoria/{grupoProyectoId}/{categoriaId}
    defaults: { _controller: "SieOlimpiadasBundle:OlimRobotica:actualizarCategoria" }
    options:
        expose: true