tramite_detalle:
    path:     /
    defaults: { _controller: SieTramitesBundle:Default:Generar }

# CERTIFICACION TÃ‰CNICA

tramite_detalle_certificado_tecnico_recepcion_busca:
    path:     /certificado/tecnico/recepcion/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecRecepcionBusca }

tramite_detalle_certificado_tecnico_recepcion_lista:
    path:     /certificado/tecnico/recepcion/lista
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecRecepcionLista }

tramite_detalle_certificado_tecnico_recepcion_lista_pdf:
    path:     /certificado/tecnico/recepcion/lista/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecRecepcionListaPdf }

tramite_detalle_certificado_tecnico_recepcion_guarda:
    path:     /certificado/tecnico/recepcion/guarda
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecRecepcionGuarda }

tramite_detalle_certificado_tecnico_autorizacion_busca:
    path:     /certificado/tecnico/autorizacion/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecAutorizacionBusca }

tramite_detalle_certificado_tecnico_autorizacion_lista:
    path:     /certificado/tecnico/autorizacion/lista
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecAutorizacionLista }

tramite_detalle_certificado_tecnico_autorizacion_lista_pdf:
    path:     /certificado/tecnico/autorizacion/lista/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecAutorizacionListaPdf }

tramite_detalle_certificado_tecnico_autorizacion_guarda:
    path:     /certificado/tecnico/autorizacion/guarda
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecAutorizacionGuarda }

tramite_detalle_certificado_tecnico_impresion_busca:
    path:     /certificado/tecnico/impresion/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecImpresionBusca }

tramite_detalle_certificado_tecnico_impresion_lista:
    path:     /certificado/tecnico/impresion/lista
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecImpresionLista }

tramite_detalle_certificado_tecnico_impresion_lista_pdf:
    path:     /certificado/tecnico/impresion/lista/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecImpresionListaPdf }

tramite_detalle_certificado_tecnico_impresion_certificado_pdf:
    path:     /certificado/tecnico/impresion/certificado/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecImpresionCertificadoPdf }

tramite_detalle_certificado_tecnico_impresion_certificado_ci_pdf:
    path:     /certificado/tecnico/impresion/certificado/ci/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecImpresionCertificadoCiPdf }

tramite_detalle_certificado_tecnico_impresion_certificado_firma_pdf:
    path:     /certificado/tecnico/impresion/certificado/firma/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecImpresionCertificadoFirmaPdf }

tramite_detalle_certificado_tecnico_impresion_guarda:
    path:     /certificado/tecnico/impresion/guarda
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecImpresionGuarda }

tramite_detalle_certificado_tecnico_envio_busca:
    path:     /certificado/tecnico/envio/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecEnvioBusca }

tramite_detalle_certificado_tecnico_envio_lista:
    path:     /certificado/tecnico/envio/lista
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecEnvioLista }

tramite_detalle_certificado_tecnico_envio_lista_pdf:
    path:     /certificado/tecnico/envio/lista/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecEnvioListaPdf }

tramite_detalle_certificado_tecnico_envio_guarda:
    path:     /certificado/tecnico/envio/guarda
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecEnvioGuarda }

tramite_detalle_certificado_tecnico_entrega_busca:
    path:     /certificado/tecnico/entrega/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecEntregaBusca }

tramite_detalle_certificado_tecnico_entrega_lista:
    path:     /certificado/tecnico/entrega/lista
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecEntregaLista }

tramite_detalle_certificado_tecnico_entrega_lista_pdf:
    path:     /certificado/tecnico/entrega/lista/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecEntregaListaPdf }

tramite_detalle_certificado_tecnico_entrega_guarda:
    path:     /certificado/tecnico/entrega/guarda
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:certTecEntregaGuarda }

# DIPLOMA HUMANISTICO

tramite_detalle_diploma_humanistico_recepcion_busca:
    path:     /diploma/humanistico/recepcion/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumRecepcionBusca }

tramite_detalle_diploma_humanistico_recepcion_lista:
    path:     /diploma/humanistico/recepcion/lista
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumRecepcionLista }

tramite_detalle_diploma_humanistico_recepcion_lista_pdf:
    path:     /diploma/humanistico/recepcion/lista/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumRecepcionListaPdf }

tramite_detalle_diploma_humanistico_recepcion_guarda:
    path:     /diploma/humanistico/recepcion/guarda
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumRecepcionGuarda }

tramite_detalle_diploma_humanistico_autorizacion_busca:
    path:     /diploma/humanistico/autorizacion/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumAutorizacionBusca }

tramite_detalle_diploma_humanistico_autorizacion_lista:
    path:     /diploma/humanistico/autorizacion/lista
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumAutorizacionLista }

tramite_detalle_diploma_humanistico_autorizacion_lista_pdf:
    path:     /diploma/humanistico/autorizacion/lista/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumAutorizacionListaPdf }

tramite_detalle_diploma_humanistico_autorizacion_guarda:
    path:     /diploma/humanistico/autorizacion/guarda
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumAutorizacionGuarda }

tramite_detalle_diploma_humanistico_impresion_busca:
    path:     /diploma/humanistico/impresion/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumImpresionBusca }

tramite_detalle_diploma_humanistico_impresion_lista:
    path:     /diploma/humanistico/impresion/lista
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumImpresionLista }

tramite_detalle_diploma_humanistico_impresion_acta_busca:
    path:     /diploma/humanistico/impresion/acta/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumImpresionActaBusca }

tramite_detalle_diploma_humanistico_impresion_acta_lista:
    path:     /diploma/humanistico/impresion/acta/lista
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumImpresionActaLista }

tramite_detalle_diploma_humanistico_impresion_acta_pdf:
    path:     /diploma/humanistico/impresion/acta/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumImpresionActaPdf }

tramite_detalle_diploma_humanistico_impresion_carton_busca:
    path:     /diploma/humanistico/impresion/carton/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumImpresionCartonBusca }

tramite_detalle_diploma_humanistico_impresion_carton_pdf:
    path:     /diploma/humanistico/impresion/carton/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumImpresionCartonPdf }

tramite_detalle_diploma_humanistico_impresion_carton_lote_busca:
    path:     /diploma/humanistico/impresion/carton/lote/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumImpresionCartonLoteBusca }

tramite_detalle_diploma_humanistico_impresion_carton_lote_pdf:
    path:     /diploma/humanistico/impresion/carton/lote/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumImpresionCartonLotePdf }

tramite_detalle_diploma_humanistico_impresion_guarda:
    path:     /diploma/humanistico/impresion/guarda
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumImpresionGuarda }

tramite_detalle_diploma_humanistico_envio_busca:
    path:     /diploma/humanistico/envio/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumEnvioBusca }

tramite_detalle_diploma_humanistico_envio_lista:
    path:     /diploma/humanistico/envio/lista
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumEnvioLista }

tramite_detalle_diploma_humanistico_envio_lista_pdf:
    path:     /diploma/humanistico/envio/lista/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumEnvioListaPdf }

tramite_detalle_diploma_humanistico_envio_guarda:
    path:     /diploma/humanistico/envio/guarda
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumEnvioGuarda }

tramite_detalle_diploma_humanistico_entrega_busca:
    path:     /diploma/humanistico/entrega/busca
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumEntregaBusca }

tramite_detalle_diploma_humanistico_entrega_lista:
    path:     /diploma/humanistico/entrega/lista
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumEntregaLista }

tramite_detalle_diploma_humanistico_entrega_lista_pdf:
    path:     /diploma/humanistico/entrega/lista/pdf
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumEntregaListaPdf }

tramite_detalle_diploma_humanistico_entrega_guarda:
    path:     /diploma/humanistico/entrega/guarda
    defaults: { _controller: SieTramitesBundle:TramiteDetalle:dipHumEntregaGuarda }
