sie_herramienta_info_estudianteRudeNuevo:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoEstudianteRudeNuevo.yml"
    prefix:   /sie/infoEstudianteRudeNuevo

sie_herramienta_info_estudianteRude:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoEstudianteRude.yml"
    prefix:   /sie/infoEstudianteRude

sie_herramienta_info_estudianteDatosCurso:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoEstudianteDatosCurso.yml"
    prefix:   /sie/infoEstudianteDatosCurso

sie_herramienta_homepage:
    path:     /hello/{name}
    defaults: { _controller: SieHerramientaBundle:Default:index }

sie_app_web_inscription_ue_all:
    resource: "@SieHerramientaBundle/Resources/config/routing/inscriptionUeAll.yml"
    prefix:   /sie/inscriptionUeAll

sie_herramienta_students_inscriptions_seguimiento:
    resource: "@SieHerramientaBundle/Resources/config/routing/studentsInscriptionSeguimiento.yml"
    prefix:   /sie/estudiantesInscritoSeguimiento

sie_app_web_areas:
    resource: "@SieHerramientaBundle/Resources/config/routing/adicioneliminacionareas.yml"
    prefix:   /sie/adicionEliminacionAreas

sie_regular_notas_cualitativas:
    resource: "@SieHerramientaBundle/Resources/config/routing/notascualitativas.yml"
    prefix:   /sie/notascualitativas

sie_regular_notas:
    resource: "@SieHerramientaBundle/Resources/config/routing/notas.yml"
    prefix:   /sie/notas

sie_herramienta_inbox:
    resource: "@SieHerramientaBundle/Resources/config/routing/inbox.yml"
    prefix:   /sie/inbox

sie_herramienta_inboxrequest:
    resource: "@SieHerramientaBundle/Resources/config/routing/inboxrequest.yml"
    prefix:   /sie/inboxrequest

sie_herramienta_info_ueducativa:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoUeducativa.yml"
    prefix:   /sie/infoUeducativa

sie_herramienta_info_personal_adm:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoPersonalAdm.yml"
    prefix:   /acceso/infoPersonalAdm

sie_herramienta_info_maestro:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoMaestro.yml"
    prefix:   /acceso/infoMaestro

sie_herramienta_info_maestro_planilla:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoMaestroPlanilla.yml"
    prefix:   /acceso/infoMaestroPlanilla

sie_herramienta_info_estudiante:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoEstudiante.yml"
    prefix:   /sie/infoEstudiante

sie_herramienta_info_estudiante_asignar_paralelo:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoEstudianteAsignarParalelo.yml"
    prefix:   /sie/infoEstudiante

sie_herramienta_info_estudianterequest:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoEstudianterequest.yml"
    prefix:   /sie/infoEstudianteRequest

sie_herramienta_ieducativa:
    resource: "@SieHerramientaBundle/Resources/config/routing/ieducativa.yml"
    prefix:   /sie/infoIeducativa

sie_herramienta_ieducativa_equipamiento_laboratorio:
    resource: "@SieHerramientaBundle/Resources/config/routing/ieducativaEquipamientoLaboratorio.yml"
    prefix:   /sie/infoIeducativa/equipamiento/laboratorio

sie_herramienta_mallacurricular:
    resource: "@SieHerramientaBundle/Resources/config/routing/mallacurricular.yml"
    prefix:   /sie/malla

sie_herramienta_creacion_cursos:
    resource: "@SieHerramientaBundle/Resources/config/routing/creacioncursos.yml"
    prefix:   /sie/crearCursos

sie_herramienta_inscription_tecnica:
    resource: "@SieHerramientaBundle/Resources/config/routing/inscriptionTecnica.yml"
    prefix:   /sie/inscriptiontec

sie_herramienta_info_tecnica:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoTecnica.yml"
    prefix:   /sie/infotecnica

sie_herramienta_cursos_tecnica:
    resource: "@SieHerramientaBundle/Resources/config/routing/cursosTecnica.yml"
    prefix:   /sie/cursostecnica

sie_herramienta_estudiantes_tecnica:
    resource: "@SieHerramientaBundle/Resources/config/routing/estudiantesTecnica.yml"
    prefix:   /sie/estudiantestecnica

sie_herramienta_change_paralelo:
    resource: "@SieHerramientaBundle/Resources/config/routing/cambioParalelo.yml"
    prefix:   /sie/cambioparalelo

sie_herramienta_tramite:
    resource: "@SieHerramientaBundle/Resources/config/routing/tramite.yml"
    prefix:   /sie/tramiteAcademico

sie_herramienta_findsie:
    resource: "@SieHerramientaBundle/Resources/config/routing/findsie.yml"
    prefix:   /sie/findsie

sie_herramienta_newspeciality:
    resource: "@SieHerramientaBundle/Resources/config/routing/newspeciality.yml"
    prefix:   /sie/newspeciality

sie_herramienta_apoderado_estudiante:
    resource: "@SieHerramientaBundle/Resources/config/routing/apoderadoestudiante.yml"
    prefix:   /sie/apoderadoestudiante

sie_herramienta_info_estudiante_bjp:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoEstudianteBjp.yml"
    prefix:   /sie/infoEstudianteBjp

sie_herramienta_up_file_bjp:
    resource: "@SieHerramientaBundle/Resources/config/routing/upfileue.yml"
    prefix:   /sie/upfileue

sie_herramienta_infoconsolidation:
    resource: "@SieHerramientaBundle/Resources/config/routing/infoConsolidation.yml"
    prefix:   /sie/infoConsolidation

sie_herramienta_donwload_file_sie:
    resource: "@SieHerramientaBundle/Resources/config/routing/downloadFileSieAcademico.yml"
    prefix:   /sie/downloadFileSieAcademico

sie_herramienta_estudiante_socieconomico:
    resource: "@SieHerramientaBundle/Resources/config/routing/estudianteSocioeconomico.yml"
    prefix:   /sie/estudiantesocioeconomico

sie_herramienta_aca_multigrado:
    resource: "@SieHerramientaBundle/Resources/config/routing/acamultigrado.yml"
    prefix:   /sie/acamultigrado

sie_herramienta_solicitud_bth:
    resource: "@SieHerramientaBundle/Resources/config/routing/solicitudBTH.yml"
    prefix:   /sie/tramite/solicitudbth

sie_herramienta_encuesta_ue:
    resource: "@SieHerramientaBundle/Resources/config/routing/encuestaUe.yml"
    prefix:   /sie/encuestaUe    


#sie_herramienta_wf_tramite:
#    resource: "@SieAppWebBundle/Resources/config/routing/wftramite.yml"
#    prefix:   /sie/tramite

# sie_herramienta_tramite_rue:
#     resource: "@SieHerramientaBundle/Resources/config/routing/tramiterue.yml"
#     prefix:   /tramiterue

sie_herramienta_consultas:
    resource: "@SieHerramientaBundle/Resources/config/routing/consultas.yml"
    prefix:   /sie/consultasmaestros

sie_herramienta_regularization_docente:
    resource: "@SieHerramientaBundle/Resources/config/routing/regularizationlistdocente.yml"
    prefix:   /sie/regularizationlistdocente

# sie_herramienta_regularization_docente_to_distrito:
#     resource: "@SieHerramientaBundle/Resources/config/routing/regularizationlistdocentetodistrito.yml"
#     prefix:   /sie/regularizationlistdocente

sie_herramienta_regularizacion_cut:
    resource: "@SieHerramientaBundle/Resources/config/routing/regularizationCUT.yml"
    prefix:   /sie/regcut

sie_herramienta_reportelabofisquim:
    resource: "@SieHerramientaBundle/Resources/config/routing/reportelabofisquim.yml"
    prefix:   /sie/labofisquim

sie_herramienta_estadistica_bth:
    resource: "@SieHerramientaBundle/Resources/config/routing/estadisticaBth.yml"
    prefix:   /estadistica/bth

sie_herramienta_estadistica_modular:
    resource: "@SieHerramientaBundle/Resources/config/routing/estadisticaModular.yml"
    prefix:   /estadistica/modular

sie_herramienta_estudianteTrabajaNuevo:
    resource: "@SieHerramientaBundle/Resources/config/routing/estudianteTrabajaNuevo.yml"
    prefix:   /sie/estudianteTrabajaNuevo    

sie_herramienta_estudianteTrabaja:
    resource: "@SieHerramientaBundle/Resources/config/routing/estudianteTrabaja.yml"
    prefix:   /sie/estudianteTrabaja

sie_herramienta_nnats:
    resource: "@SieHerramientaBundle/Resources/config/routing/reportesNnats.yml"
    prefix:   /sie/Nnats

sie_herramienta_registro_promotor:
    resource: "@SieHerramientaBundle/Resources/config/routing/promotor.yml"
    prefix:   /sie/promotor

sie_herramienta_registro_evento:
    resource: "@SieHerramientaBundle/Resources/config/routing/regevent.yml"
    prefix:   /sie/regevent

sie_herramienta_registro_resultado:
    resource: "@SieHerramientaBundle/Resources/config/routing/regresultevent.yml"
    prefix:   /sie/regresultevent

sie_herramienta_registro_estudiante:
     resource: "@SieHerramientaBundle/Resources/config/routing/regstudent.yml"
     prefix:   /sie/regstudent

sie_herramienta_cdl_seguimiento:
    resource: "@SieHerramientaBundle/Resources/config/routing/cdlseguimiento.yml"
    prefix:   /sie/cdlseguimiento

sie_herramienta_anular_bth:
     resource: "@SieHerramientaBundle/Resources/config/routing/anularBTH.yml"
     prefix:   /sie/anularbth

sie_newrequestbth:
     resource: "@SieHerramientaBundle/Resources/config/routing/newrequestbth.yml"
     prefix:   /sie/newrequestbth

sie_upinfrafile:
     resource: "@SieHerramientaBundle/Resources/config/routing/upinfrafile.yml"
     prefix:   /sie/upinfrafile

sie_downloadinfrafile:
     resource: "@SieHerramientaBundle/Resources/config/routing/downloadinfrafile.yml"
     prefix:   /sie/downloadinfrafile

sie_newinscriptionInipri:
     resource: "@SieHerramientaBundle/Resources/config/routing/newinscriptionInipri.yml"
     prefix:   /sie/newinscriptionInipri

sie_apoderado_nuevo:
     resource: "@SieHerramientaBundle/Resources/config/routing/apoderadoNuevo.yml"
     prefix:   /sie/apoderadoNuevo

sie_transfer_students:
     resource: "@SieHerramientaBundle/Resources/config/routing/transferstudents.yml"
     prefix:   /sie/transferstudents

sie_apoderado_bono_familia:
     resource: "@SieHerramientaBundle/Resources/config/routing/apoderadoBonoFamilia.yml"
     prefix:   /sie/apoderado-bono-familia


sie_unidadeducativa_plataforma:
     resource: "@SieHerramientaBundle/Resources/config/routing/unidadeducativaplataforma.yml"
     prefix:   /sie/plataforma

sie_registerforeignerperson:
     resource: "@SieHerramientaBundle/Resources/config/routing/registerforeignerperson.yml"
     prefix:   /sie/registerforeignerperson

sie_unidadeducativa_selectedStudents:
     resource: "@SieHerramientaBundle/Resources/config/routing/selectedstudents.yml"
     prefix:   /sie/selectedstudents

sie_regularizacion_rue:
    resource: "@SieHerramientaBundle/Resources/config/routing/regularizacionRue.yml"
    prefix: /sie/regularizarRue


#Ruta para el operativo de salud
sie_herramienta_info_operativo_salud_administrativo_maestro:
    resource: "@SieHerramientaBundle/Resources/config/routing/operativoSaludAdministrativoMaestro.yml"
    prefix:   /acceso/operativo-salud/administrativo-maestro

sie_gestiones_pasadas_areas_estudiante:
    resource: "@SieHerramientaBundle/Resources/config/routing/gestPasadasAreasEstudiante.yml"
    prefix: /sie/gestPasadasAreasEstudiante

#sie_unidadeducativa_regularizacionGestionesPasadas:
#     resource: "@SieHerramientaBundle/Resources/config/routing/regularizacionGestionesPasadas.yml"
#     prefix:   /sie/regularizacion-gestiones-pasadas


#caso 3 regularizaion de notas gestion pasada
sie_regularizacion_regularizacionEstudiantesPostBachillerato:
     resource: "@SieHerramientaBundle/Resources/config/routing/regularizacionEstudiantesPostBachillerato.yml"
     prefix:   /sie/regularizacion-estudiantes-post-bachillerato
#     
#     

sie_institucioneducativa_acceso_internet:
    resource: "@SieHerramientaBundle/Resources/config/routing/institucioneducativaAccesoInternet.yml"
    prefix: /sie/institucioneducativaAccesoInternet

sie_institucioneducativa_report_vul:
    resource: "@SieHerramientaBundle/Resources/config/routing/reportstudentvulnerability.yml"
    prefix: /sie/reportVul

sie_tramite_gp_areasestudiante:
    resource: "@SieHerramientaBundle/Resources/config/routing/tramitegpareasestudiante.yml"
    prefix:   /sie/tramite/areasestudiante


# operativo bono JP
sie_operativo_bonojp:
    resource: "@SieHerramientaBundle/Resources/config/routing/operativoBonoJP.yml"
    prefix:   /operativo-bonojp

sie_academico_UpdatePlaceDataStudent:
    resource: "@SieHerramientaBundle/Resources/config/routing/updateplaceDatastudent.yml"
    prefix:   /sie/updateplacedatastudent

sie_regularizacion_IncoherenciasExterior:
    resource: "@SieHerramientaBundle/Resources/config/routing/regularizacionincoherenciasexterior.yml"
    prefix:   /sie/regularizacionGPIncoherenciasEXterior


# preinscripciones
sie_preinscripciones:
    resource: "@SieHerramientaBundle/Resources/config/routing/preinscripciones.yml"
    prefix:   /preinscripciones

sie_preinscripcion_sorteo_padre:
    resource: "@SieHerramientaBundle/Resources/config/routing/preinscripcionsorteohijo.yml"
    prefix: /sie/sorteopreinscripcion


sie_chees_event:
     resource: "@SieHerramientaBundle/Resources/config/routing/cheesevent.yml"
     prefix:   /sie/cheesevent

sie_chees_event_adm:
     resource: "@SieHerramientaBundle/Resources/config/routing/cheeseventadm.yml"
     prefix:   /sie/cheeseventadm

sie_adm_chees_event:
     resource: "@SieHerramientaBundle/Resources/config/routing/admcheesevent.yml"
     prefix:   /sie/admcheesevent


sie_censoinscription:
     resource: "@SieHerramientaBundle/Resources/config/routing/censoinscription.yml"
     prefix:   /sie/censo

sie_talentoinscription:
     resource: "@SieHerramientaBundle/Resources/config/routing/talentoinscription.yml"
     prefix:   /sie/evetalento

sie_adm_inscriptalento_event:
     resource: "@SieHerramientaBundle/Resources/config/routing/adminscriptalento.yml"
     prefix:   /sie/adminscriptalento

sie_managerinstalento:
     resource: "@SieHerramientaBundle/Resources/config/routing/managerinstalento.yml"
     prefix:   /sie/managertalento     

sie_adm_pla:
     resource: "@SieHerramientaBundle/Resources/config/routing/admpla.yml"
     prefix:   /sie/admplan
# sie_censoinscription:
#      resource: "@SieHerramientaBundle/Resources/config/routing/censoinscription.yml"
#      prefix:   /sie/censo

# index:
#     path:     /index
#     defaults: { _controller: SieHerramientaBundle:ChessEventAdm:index }

# index:
#     path:     /index
#     defaults: { _controller: SieHerramientaBundle:newInscriptiontoDirector:index }

# index:
#     path:     /index
#     defaults: { _controller: SieHerramientaBundle:AdmInscripTalento:index }

# index:
#     path:     /index
#     defaults: { _controller: SieHerramientaBundle:ManagerInsTalento:index }

# index:
#     path:     /index
#     defaults: { _controller: SieHerramientaBundle:AdmPla:index }

sie_regularizacion_bth_ttg_tte:
     resource: "@SieHerramientaBundle/Resources/config/routing/bthregularizacionttgtte.yml"
     prefix:   /sie/rbtt
