herramienta_inbox_index:
    path:     /
    defaults: { _controller: SieHerramientaBundle:Inbox:index}

herramienta_inbox_open:
    path:     /sie/open
    defaults: { _controller: SieHerramientaBundle:Inbox:open}

notas_cargar_turnos:
    path:     /cargarTurnos/{idInstitucion}/{gestion}/
    defaults: { _controller: "SieHerramientaBundle:Inbox:cargarTurnos"}
    options:
         expose: true

herramienta_inbox_openbygestion:
    path:     /sie/open/{number}/
    defaults: { _controller: SieHerramientaBundle:Inbox:openByGestion}

herramienta_inbox_openbygestion_tramite:
    path:     /sie/regularizarUe/
    defaults: { _controller: SieHerramientaBundle:Inbox:openByGestionTramite}

herramienta_inbox_close_operativo:
    path:     /closeoperativo
    defaults: { _controller: "SieHerramientaBundle:Inbox:closeOperativo"}
    options:
         expose: true

herramienta_inbox_downoperativorude:
    path:     /downoperativorude
    defaults: { _controller: "SieHerramientaBundle:Inbox:downOperativoRude"}
    options:
         expose: true

herramienta_inbox_downloadRude:
    path:     /download/{file}/{datadownload}
    defaults: { _controller: "SieHerramientaBundle:Inbox:download"}
    options:
         expose: true


herramienta_inbox_close_operativo_rude:
    path:     /closeoperativo-rude
    defaults: { _controller: "SieHerramientaBundle:Inbox:closeOperativoRude"}
    options:
         expose: true

herramienta_inbox_close_operativo_inscription:
    path:     /closeoperativo-inscription
    defaults: { _controller: "SieHerramientaBundle:Inbox:closeOperativoInscription"}
    options:
         expose: true

herramienta_inbox_close_operativo_forzar:
    path:     /closeoperativo-forzar
    defaults: { _controller: "SieHerramientaBundle:Inbox:closeOperativoForzado"}
    options:
         expose: true
