herramienta_infoEstudianteDatosCurso_index:
    path:     /index
    defaults: { _controller: "SieHerramientaBundle:InfoEstudianteDatosCurso:index"}
    options:
         expose: true

herramienta_infoEstudianteDatosCurso_save:
    path:     /save
    defaults: { _controller: "SieHerramientaBundle:InfoEstudianteDatosCurso:save"}
    options:
         expose: true

herramienta_modalidadCurso_index:
    path:     /indexModalidad
    defaults: { _controller: "SieHerramientaBundle:ModalidadCurso:index"}
    options:
         expose: true

herramienta_modalidadCurso_save:
    path:     /saveModalidad
    defaults: { _controller: "SieHerramientaBundle:ModalidadCurso:save"}
    options:
         expose: true

#Texto Educativo
herramienta_textoEducativo_index:
    path:     /TextoEducativo
    defaults: { _controller: "SieHerramientaBundle:TextoEducativo:index"}
    options:
         expose: true

herramienta_textoEducativo_save:
    path:     /saveTextoEducativo
    defaults: { _controller: "SieHerramientaBundle:TextoEducativo:save"}
    options:
         expose: true

herramienta_textoEducativo_delete:
    path:     /deleteTextoEducativo/{id}
    defaults: { _controller: "SieHerramientaBundle:TextoEducativo:delete"}
    options:
         expose: true

herramienta_textoEducativo_seguimiento:
    path:     /seguimientoOperativoTextoEducativo
    defaults: { _controller: "SieHerramientaBundle:TextoEducativo:seguimiento"}
    options:
         expose: true

herramienta_textoEducativo_seguimiento_mostrarDatos:
    path:     /mostrarDatosSeguimiento
    defaults: { _controller: "SieHerramientaBundle:TextoEducativo:mostrarDatos"}
    options:
         expose: true

herramienta_textoEducativo_getUEs:
    path:     /getUEs/{distrito}
    defaults: { _controller: "SieHerramientaBundle:TextoEducativo:getUnidadesEducativas"}
    options:
         expose: true

herramienta_textoEducativo_generarReporte:
    path:     /reporte/{sie}/{gestion}
    defaults: { _controller: "SieHerramientaBundle:TextoEducativo:generarReporte"}
    options:
         expose: true

herramienta_modulosCurso_index:
    path:     /indexModulosCurso
    defaults: { _controller: "SieHerramientaBundle:ModalidadCurso:getModulos2024"}
    options:
         expose: true

