herramienta_infoconsolidation_index:
    path:     /
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:index }

herramienta_infoconsolidation_find:
    path:     /sie/find
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:find }

herramienta_infoconsolidation_gestion_index:
    path:     /consolgestion
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:consolidacionGestion }

herramienta_inforeporte_modalidad_atencion:
    path:     /reporte_modalidad_atencion
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:reporteModalidadAtencion }

herramienta_inforeporte_inicio_actividades:
    path:     /reporte_inicio_actividades/
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:reporteInicioActividades }
    methods:  ['GET','POST']

herramienta_inforeporte_inicio_actividades_distrito:
    path:     /reporte_inicio_actividades/distrito/
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:reporteInicioActividadesDistrito }
    methods:  ['GET','POST']

herramienta_inforeporte_inicio_actividades_distrito_colegio:
    path:     /reporte_inicio_actividades/distrito/colegio/
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:reporteInicioActividadesColegio }
    methods:  ['GET','POST']
    
herramienta_inforeporte_estudiantes_en_situacion_de_vulnerabilidad:
    path:     /reporte-estudiantes-situacion-vulnerabilidad
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:reporteEstudiantesSituacionVulnerabilidad }
    methods:  ['GET','POST']

herramienta_infoconsolidation_enabledOpe:
    path:     /enabledOpe/{sie}/{gestion}
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:enabledOpe }    

herramienta_infoconsolidation_habilitarOpe:
    path:     /habilitarOpe/{sie}/{gestion}
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:habilitarOpe }   
    
herramienta_infoconsolidation_gestion_inconsistencias_index:
    path:     /consolgestionincosistencias
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:consolidacionGestionInconsistencias }

herramienta_infoconsolidation_gestion_inconsistencias_modal:
    path:     /{gestionid}/consolgestionincosistenciasmodal
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:getInconsistencias }

herramienta_infoconsolidation_gestion_sexto:
    path:     /consolsexto
    defaults: { _controller: SieHerramientaBundle:InfoConsolidation:consolidacionSexto }

  
   